### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by castillop** [claudiocu81/SkinTearsApp#1]
The code documentation should be improved taking advantage of GitHub tools.

e.g. 
  - https://blog.github.com/2016-08-22-publish-your-project-documentation-with-github-pages/
  - https://github.com/kriasoft/Folder-Structure-Conventions
  - https://guides.github.com/features/wikis/

**Comment by claudiocu81** [comment]
Closed en 4709421f443a4072a66d794e9ce28adf8a24be60

**Comment by castillop** [comment]
The main page describes well enough the first steps to enable the test version, but it lacks an insight describing the intended use and some examples on how to operate the application.

Please, provide at least one use case. Images are encouraged.

**Comment by claudiocu81** [comment]
Se ingresa proceso de uso del módulo para subir imágenes, también se inserta un Gif que explica el proceso.

Commit 7171a5a6fb7e00bd65f3e4dcbfcb5a7bfe5c373e
Commit 042ee153857e972655c4b00eeda7dab253faac45
